<?php

/**
 * PluginacContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginacContact extends BaseacContact
{
	public function getEmailForSwift()
	{
		$fields = sfConfig::get('app_ac_contact_sender_name_fields');
		$sender_name = '';
		foreach($fields as $field)
		{
			if ($sender_name) 
				$sender_name .= ' ';
			$sender_name .= $this->$field;
		}
		if (!$sender_name) 
			$sender_name = $this->email; 
		
		return array($this->email => $sender_name);
	}

	public function getSubject()
	{
		return 'Contatto inviato tramite il sito '.$_SERVER['HTTP_HOST'];
	}
	
	public function getBody()
	{
		$body = '';
		foreach(sfConfig::get('app_ac_contact_schema') as $key => $field)
		{
			$body .= $field['name'].': '.$this->$field['name']."\n";
		}
		return $body;
	}
	
	public function getHtmlBody()
	{
		return str_replace("\n",'<br/>',$this->getBody());
	}
}
