<?php

/**
 * PluginacContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginacContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginacContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginacContact');
    }
}